### ISSUE TITLE
Change tooltip to show start and end timestamp, not just "time"

### ISSUE THREAD

**Issue by ErikBjare** [ActivityWatch/aw-webui#109]
Hard to figure out the duration of gaps otherwise, which I needed to know when debugging.

**Comment by johan-bjareholt** [comment]
Tooltip where?

**Comment by ErikBjare** [comment]
@johan-bjareholt Timeline currently, but tool-tip generation is generalized in: https://github.com/ActivityWatch/aw-webui/blob/master/src/util/tooltip.js

**Comment by ErikBjare** [comment]
This was done a while back, closing.
