### ISSUE TITLE
Browser activity missing for firefox

### ISSUE THREAD

**Issue by vesatoivonen** [ActivityWatch/aw-webui#120]
I'm on version v0.8.0b7 and using `aw-watcher-web-chrome` and `aw-watcher-web-firefox`.
Firefox bucket is always empty on activity tab, but on timeline I can see that firefox data is collected.
Chrome's data is shown propery on both views.

![screenshot_2019-01-18_11-09-34](https://user-images.githubusercontent.com/3157489/51377006-a5145080-1b01-11e9-93dc-d5f31b62f668.png)
![screenshot_2019-01-18_11-10-22](https://user-images.githubusercontent.com/3157489/51377148-0d633200-1b02-11e9-9637-a970aec28d03.png)

**Comment by vesatoivonen** [comment]
I poked around a bit and it seems that this happens because I'm using Firefox Nightly and the filters used in the query don't match it.
Adding `FirefoxNightly` to `browser_appnames` on queries.js should fix this, at least for me.

**Comment by johan-bjareholt** [comment]
For the web activity to be visible we also need aw-watcher-afk and aw-watcher-window to run at the same time. I can see in your timeline that aw-watcher-afk is working well (you have afk and not-afk events) but it seems like aw-watcher-window has not created any events in the timeline?
aw-watcher-window is needed so aw-server can know when the browser window is focused and not.

**Comment by johan-bjareholt** [comment]
@vesatoivonen Well, that is also certainly a reason why it's not working!
Will you do a PR or should I add it to aw-webui?

**Comment by vesatoivonen** [comment]
It would be great if you could add it, I'm not familiar enough with the project yet.
I confirmed by curling that the appname working for me is `FirefoxNightly`.
On mac and windows this might be something else.

**Comment by johan-bjareholt** [comment]
Are you sure that the appname is exactly "FirefoxNightly"? No spaces or anything?
The other appnames we have seem to have spaces so I assume that this one might aswell, but it could also be a mistake on Firefox part.
These are the other appnames for firefox: `["Firefox", "Firefox.exe", "firefox", "firefox.exe", "Firefox Developer Edition", "Firefox Beta"]`

**Comment by vesatoivonen** [comment]
Yeah, no spaces. This is a `eventmodel.datastr` straight from the db: `{"app": "FirefoxNightly", "title": "Preferences - Firefox Nightly"}`

**Comment by ErikBjare** [comment]
That's a bit weird though, I thought we had them nailed down in this PR: https://github.com/ActivityWatch/aw-webui/pull/111

Perhaps it varies between desktop environments or something? Idk.

**Comment by johan-bjareholt** [comment]
@ErikBjare It's not wierd, we have firefox beta and firefox developer edition but not firefox nightly so it makes sense.

**Comment by ErikBjare** [comment]
Should have been fixed in #121, closing.
