### ISSUE TITLE
No data on Summary page - status code 400

### ISSUE THREAD

**Issue by jon-chard** [ActivityWatch/aw-webui#133]
Have installed the latest version (Version: v0.8.0b7) of Activity Watcher on MacOS Mojave, V10.14.3

On the Activity page, I get no data on the summary page - dashboard widgets show 'Loading...' and the page shows an error message
"Error: Request failed with status code 400. See dev console (F12) and/or server logs for more info. "

The Window tab on the Activity page shows info, as does the Timeline view so the data is there.

Problem visible in Chrome, Firefox and Safari (latest of all)

**Comment by johan-bjareholt** [comment]
> On the Activity page, I get no data on the summary page - dashboard widgets show 'Loading...' and the page shows an error message

There are many widgets on the summary page, are none of them loading?

> "Error: Request failed with status code 400. See dev console (F12) and/or server logs for more info. "

Can you press F12 and report that the error message says?

**Comment by jon-chard** [comment]
On the summary page, no widgets are loading.

In the developer console, there are many errors. Here's a selection:
Failed to load resource: the server responded with a status of 400 (BAD REQUEST) (:5600/api/0/query/:1 )

Uncaught (in promise) Error: Request failed with status code 400
    at t.exports (createError.js:16)
    at t.exports (settle.js:18)
    at XMLHttpRequest.f.(:5600/anonymous function) (http://127.0.0.1:5600/static/js/0.d7dbfdca8ba20450def7.js:40:62595)

Do I need to make sure port 5600 is open?

**Comment by jon-chard** [comment]
In the network view, I am getting responses from some queries on port 5600 so I don't think it's blocked.

This query returns an error:
Request URL: http://127.0.0.1:5600/api/0/query/

With response:
{"type": "QueryParseException", "message": "Invalid syntax for value to assign"}

**Comment by ErikBjare** [comment]
@jon-chard What version does it say you are running in the bottom of the web UI? Try installing the latest version (v0.8.0b8)

**Comment by jon-chard** [comment]
Ok, I'm on b7. Will try upgrading.

**Comment by jon-chard** [comment]
Have upgraded - sorry, it's the same.

**Comment by johan-bjareholt** [comment]
> `aw_analysis.query2_error.QueryParseException: Invalid syntax for value to assign`

This indicates that the query request in aw-webui is invalid or has somehow become malformed, can you go to the "Network" tab in F12, refresh the page, find the 400 query request and paste the request body (In firefox the sub-tab is called "Params", should be something similar in Chrome)

This should give us a good clue of what's wrong with the query.

**Comment by jon-chard** [comment]
The request 'payload' is:

{"query":["events = flood(query_bucket(\"aw-watcher-web-chrome\"));","window_browser = flood(query_bucket(\"aw-watcher-window_Jon's MacBook Pro\"));","window_browser = filter_keyvals(window_browser, \"app\", [\"Google-chrome\",\"chrome.exe\",\"Chromium\",\"Google Chrome\",\"Chromium-browser\",\"Chromium-browser-chromium\",\"Google-chrome-beta\",\"Google-chrome-unstable\"]);","not_afk = flood(query_bucket(\"aw-watcher-afk_Jon's MacBook Pro\"));","not_afk = filter_keyvals(not_afk, \"status\", [\"not-afk\"]);","window_browser = filter_period_intersect(window_browser, not_afk);","events = filter_period_intersect(events, window_browser);","events = split_url_events(events);","urls = merge_events_by_keys(events, [\"url\"]);","urls = sort_by_duration(urls);","urls = limit_events(urls, 5);","domains = split_url_events(events);","domains = merge_events_by_keys(domains, [\"domain\"]);","domains = sort_by_duration(domains);","domains = limit_events(domains, 5);","chunks = chunk_events_by_key(events, \"domain\");","duration = sum_durations(events);","RETURN = {\"domains\": domains, \"urls\": urls, \"chunks\": chunks, \"duration\": duration};"],"timeperiods":["2019-03-13T00:00:00+00:00/2019-03-14T00:00:00+00:00"]}

OMG I bet I know what it is. Is it my macbook name? Does it need escaping?

**Comment by johan-bjareholt** [comment]
Good point, we definitely need escaping.

But in your case, your machine name contains a single quote while the string uses a double quote so it should be fine I believe. Somewhere in the code though the double quotes might be converted to single quotes though, I'm not sure. Will have to investigate.

**Comment by johan-bjareholt** [comment]
I just tried that request on my own machine and yes, removing the single quotes in the bucketname fixes the issue.
The issue goes rather deep though as it's currently not supported to escape characters in the query language, so I will have to solve that before fixing the web-ui query.

**Comment by johan-bjareholt** [comment]
I have tested and fixed this in the webui with both aw-server and aw-server-rust, please test again in the next beta release and re-open if it still doesn't work!
