### ISSUE TITLE
Add dark mode

### ISSUE THREAD

**Issue by Otto-AA** [ActivityWatch/aw-webui#143]
I think there already was an issue mentioning this, but it was postponed due to the amount of work to maintain a different style scheme. But the approach I've seen would only require about ten lines of code, so I thought I'd bring up the topic once again. It only inverts the colors which results in a dark theme.

# Screenshot
![Screenshot of dark mode](https://user-images.githubusercontent.com/21040751/58659727-022bd880-8324-11e9-8290-111029064435.png)

# Code
When darkmode is enabled a div spanning the whole screen is shown which inverts all the colors.
```text/css
width: 100vw;
height: 100vh;
position: fixed;
top: 0;
left: 0;
background: #fff;
mix-blend-mode: difference;
pointer-events: none;
```

# Thoughts
As the contrast stays the same, everything should still be readable. It's probably not the best solution, but needs very little effort to do. So implementing and maintaining* shouldn't be a problem.

*maintaining means to check if it looks fine from time to time. If a contrast is not big enough, it should be changed in the normal UI too. If a color looks bad... well it could be changed in the normal UI but I guess normal UI > dark mode then.

# Credits
I've copied the idea and code from here: https://dev.wgao19.cc/2019-05-04__sun-moon-blending-mode/

**Comment by NicoWeio** [comment]
This would result in unexpected behaviour of _category colors_ (#254) if the user switches between light/dark mode, but otherwise this sounds like a good deal.

**Comment by ErikBjare** [comment]
Fixed in https://github.com/ActivityWatch/aw-webui/pull/307
