### ISSUE TITLE
Switch from timeline-plus to vis-timeline

### ISSUE THREAD

**Issue by ErikBjare** [ActivityWatch/aw-webui#170]
timeline-plus (https://github.com/yotamberk/timeline-plus) in no longer maintained and it's features have been moved to vis-timeline (https://github.com/visjs/vis-timeline)

**Comment by xylix** [comment]
Using the newest vis-timeline (7.0.1), the timeline still gives the same infinite loop warning. Otherwise does work fine though. (available here https://github.com/xylix/aw-webui/tree/update-vis-timeline ). I'll test in non-development mode too and make a PR if it works fine.

**Comment by ErikBjare** [comment]
Ah, oh well. Feel free to open a PR anyway and I'll merge it, no need to test in non-development mode :)

**Comment by xylix** [comment]
Allright PR:ed in #171

**Comment by ErikBjare** [comment]
Thanks! 

Fixed in #171. Closing.
