### ISSUE TITLE
Wrong timeperiods for editor tab

### ISSUE THREAD

**Issue by bschwehn** [ActivityWatch/aw-webui#172]
When I open the web ui, then to activity and select a previous day (so I am looking at http://localhost:5600/#/activity/DELT0955/day/2020-02-02/)

The "Editor" tab still returns the data for the current day, not the selected day. 

For example, on the summary tab, a query is done to the api http://localhost:5600/api/0/query/ with payload ending with:

RETURN  = {\"app_events\": app_events, \"title_events\": title_events, \"cat_events\": cat_events, \"duration\": duration, \"active_events\": not_afk};"],"timeperiods":["2020-02-02T04:00:00+01:00/2020-02-03T04:00:00+01:00"]}

But on the "Editor", the query is done with payload ending with 

"RETURN = {\"files\": files, \"languages\": languages, \"projects\": projects, \"duration\": duration};"],"timeperiods":["2020-02-04T04:00:00+01:00/2020-02-05T04:00:00+01:00"]}

As you can see, the difference is that the "Summary" tab uses the selected day as timeperiods, whereas the "Editor" tab uses the current day. 

I think the intention is to also show the selected day for the editor activity instead. 

Using 0.8.4 on windows.

**Comment by johan-bjareholt** [comment]
This was fixed right after 0.8.4 was released unfortunately.
Will be fixed in the next release, sorry for not releasing more often.
https://github.com/ActivityWatch/aw-webui/pull/160

**Comment by bschwehn** [comment]
Ok, sorry, I wasn't aware that this is fixed already, thank you!

**Comment by johan-bjareholt** [comment]
Don't be sorry, I don't expect people to go search through the git log (sometimes fixes are not even mentioned there anyway).
