### ISSUE TITLE
Category sunburst issue on no data

### ISSUE THREAD

**Issue by edobry** [ActivityWatch/aw-webui#175]
When loading a summary page for a day with no data recorded, the sunburst visualization still appears, but with a `NaN`:
<img width="388" alt="Screen Shot 2020-02-24 at 11 27 50" src="https://user-images.githubusercontent.com/52695/75175553-8c14a080-5700-11ea-8164-a8161aa7c8ed.png">

**Comment by ErikBjare** [comment]
I don't really consider this a problem big enough to warrant an issue. Closing.
