### ISSUE TITLE
Display server error message if available

### ISSUE THREAD

**Issue by NicoWeio** [ActivityWatch/aw-webui#188]
I accidentally tried to open a bookmark from my PC on my laptop, pointing to
http://localhost:5600/#/activity/MYPCHOSTNAME/summary

The UI gave me an error message like this: 

> Error: Request failed with status code 400. See dev console (F12) and/or server logs for more info.

But when I looked at said response, it contained a rather useful error message: 
`{"type": "QueryFunctionException", "message": "There's no bucket named 'aw-watcher-window_<MYPCHOSTNAME>'"}`

So if the server returns human-readable and useful error messages, why not show them? For people who aren't familiar with dev tools, that would be helpful, I guess. 

PS: I could make a PR for this, if that helps.

**Comment by ErikBjare** [comment]
We've been meaning to do this, but haven't found the time. 

A PR would be very welcome :)

**Comment by NicoWeio** [comment]
Okay, I'll add it to my to-do list then.
