### ISSUE TITLE
Display errors when server cannot be reached or no host/bucket was found

### ISSUE THREAD

**Issue by ErikBjare** [ActivityWatch/aw-webui#20]
- [x] Server might not be available if running aw-webui standalone.
 - [x] Sometimes, buckets have for some reason not been created yet, this needs a good error message. 
 - [x] If no buckets have been created, then there are also no hosts since they become known first when they create a bucket. (In the Activity drop down menu, it needs clear text saying "Devices:" or something similar)

**Comment by johan-bjareholt** [comment]
Relevant

https://github.com/ActivityWatch/aw-webui/pull/14/commits/eb49ff01ec1cf2e1d0fa3710775361faa103e10b

**Comment by ErikBjare** [comment]
We've created satisfactory solutions to these problems for now, closing.
