### ISSUE TITLE
 Browser activity missing for firefox-esr

### ISSUE THREAD

**Issue by msnjuegos** [ActivityWatch/aw-webui#204]
Hello, as other users have commented for other browsers (see #120, [here](https://github.com/ActivityWatch/activitywatch/issues/321) and [here](https://github.com/ActivityWatch/activitywatch/issues/324)), I have not data displayed in the Activity --> Browser tab for my firefox web-browser (installed from debian repositories) with the firefox-plugin.

![image](https://user-images.githubusercontent.com/34399054/83816792-3b163000-a691-11ea-9594-c509c72bbd1e.png)

![image](https://user-images.githubusercontent.com/34399054/83816896-6e58bf00-a691-11ea-8d26-e4a98cdfcbde.png)

The app name displayed for my version of firefox in aw-watcher-window is: "Firefox-esr"
![image](https://user-images.githubusercontent.com/34399054/83816962-99dba980-a691-11ea-94a8-fda65fdc29b8.png)

Thanks in advance!

**Comment by ErikBjare** [comment]
Thanks for the thorough report and background research! It contains exactly what we need.

The fix was applied in https://github.com/ActivityWatch/aw-webui/commit/b6f91e3fbf2ce209a49d21045d8d5645a2e21498, and should be available in the next version.
