### ISSUE TITLE
Add proper date selector for activity view

### ISSUE THREAD

**Issue by ErikBjare** [ActivityWatch/aw-webui#22]
To make it easier to navigate further back.

Would be nice to only be able to select dates which have data for them.

**Comment by johan-bjareholt** [comment]
Was looking at trying to fix this for the dev/vue2 branch which uses bootstrap4, but apparently bootstrap4 is in alpha and does not have a datepicker yet...

And apparently the HTML5 datepicker isn't implemented in firefox yet (http://caniuse.com/#feat=input-datetime)

**Comment by ErikBjare** [comment]
I don't mind waiting a bit then. Would definitely prefer the HTML5 datepicker.

**Comment by ErikBjare** [comment]
I'm not sure if going with the HTML5 datepicker is the right way to go since there is no way to mark which dates have data and which don't (only min and max date constraints, although that might be good enough).

Still not a high priority, but something to consider.

**Comment by johan-bjareholt** [comment]
It was trivial, so added it in this PR

https://github.com/ActivityWatch/aw-webui/pull/63

Better than nothing at least

**Comment by ErikBjare** [comment]
Closing this for now, #63 seems good enough.
