### ISSUE TITLE
Show Last default not set

### ISSUE THREAD

**Issue by tngreene** [ActivityWatch/aw-webui#266]
Hi, loving this so far!

Firefox 86, ActivityWatcher 0.10.0, Win10

On the timeline view the "Show Last" drop down menu should have the default listed in the settings "For me it is 1 hour", but instead it has nothing. Kind of annoying to have to click it every time I change views.

Maybe it would be good if instead of showing a default it showed whatever was picked last time? (This might be a minor feature request, sorry)

**Comment by ErikBjare** [comment]
Fixed in master, should be working in the next release.
