### ISSUE TITLE
Dashboard, clicking on "Activity" : if there's a single host, jump directly to it

### ISSUE THREAD

**Issue by nikanar** [ActivityWatch/aw-webui#31]
When I was a first-time fresh user, I downloaded, run AW, and wanted to see data happen, to check that the program does a thing at all. I quickly found the dashboard thanks to aw-qt. There, I see tabs : "home" is a generic frontpage, server log is temporarily sick, "buckets" must be an insiders' thing for advanced users¹, so *something I can see happen* **MUST be** in the "Activity" tab (and the name gives it away nicely). 

So I clicked "Activity", and.... nothing happened ? At first I couldn't spot the difference between the following images :

![twice a similar dashboard](http://i.imgur.com/kis8DRv.png)

Long story short, if there is only one host (as there will be in many/most use cases), I think the user shouldn't have to click it, clicking on "activity" should directly move on to it.

I have little idea on how to implement that though, I guess in `App.vue`, line 28 `a(v-on:click="show_hide('views')"` should do more than that, maybe more like line 8 of `components/Views.vue` : directly a-link to `"'/activity/'+host"` (there is a single host)... someone else knows this bit of code way better than me :)

- - -

¹ At first I thought "who calls data logs 'buckets' anyway ?" and the answer is devs, who have to handle events and manage data stores to put them into. For users it's just '*magic happens*', and "buckets" mean nothing, imo. Though it's a fine name so long as AW only targets programmers :)

**Comment by johan-bjareholt** [comment]
We have some improvements on this in the dev/vue2 branch where it's a proper dropdown rather than our current homemade show_hide script which shows/hides a div which is ugly.

The current solution has a down-arrow on the button to indicate it's a dropdown button and the dropdown styling is much better aswell since it's based on bootstrap. However, I still do agree that it would be even better if it didn't show at all if there is only one host since it's simply unnecessary, but I would have to rewrite some of the code to solve that properly I believe.

Regarding the naming of the Bucket button, that is true. A better alternative would be something like "Raw data" or simply "Data" maybe?

**Comment by nikanar** [comment]
Ah alright. Indeed it's much better now, it still requires two clicks, but the unnecessary one is a lot more hinted at.

I like "raw data", referring to AW's [data philosophy](http://activitywatch.readthedocs.io/en/latest/introduction.html#data-philosophy) of storing the rawest data to allow for unforeseen future analysis, plus it gives hints that the user shouldn't expect to human-read that tab.

**Comment by johan-bjareholt** [comment]
Changed to Raw Data and changed to a database icon in commit b4cf19a

**Comment by ErikBjare** [comment]
I'd actually prefer keeping the Buckets naming and add a description to the bucket listing for clarification instead.

What do you think about that?

**Comment by johan-bjareholt** [comment]
Personally I agree what nikanar said before about that "Buckets" is confusing for non-developers, so I do not think it's a good idea. Once you have clicked on "Raw Data" I am fine with using the bucket term, but we should avoid terms that are not user friendly in the main UI.

**Comment by ErikBjare** [comment]
Alright, that's reasonable.

**Comment by ErikBjare** [comment]
So I guess we can close this now? Feel free to reply and reopen.
