### ISSUE TITLE
Year filter

### ISSUE THREAD

**Issue by Mte90** [ActivityWatch/aw-webui#313]
Right now it is possible to filter as maximum to a month but I was wondering it is possible to extend to an year with another filter in the activity.

**Comment by johan-bjareholt** [comment]
As a developer it's easy to enable, you just have to remove 3 lines of commented code in the web-ui.

It is however disabled by default due to being very slow to load. We could possibly have a feature toggle for it in the settings which could be marked as a "beta" feature.
