### ISSUE TITLE
Can't change 'Landing page' on settings page

### ISSUE THREAD

**Issue by GorlikItsMe** [ActivityWatch/aw-webui#315]
When I try change "Landing page" settings from "Home" (default) to anything else I see:
* on to of page I see alert "TypeError: t.target is undefined. See dev console (F12) and/or server logs for more info."
* in console i see this error
```
TypeError: t.target is undefined
    change LandingPageSettings.vue:1
    VueJS 4
    onChange form-select.js:83
    VueJS 9
    onChange form-select.js:81
    VueJS 3
vue.runtime.esm.js:1888:12
```

**Comment by adamczi** [comment]
Same here, but I'm getting this error also on "Start of day" and "Duration default value".

**Comment by ErikBjare** [comment]
This is fixed in master (and has been for a long time). 

Sorry for taking so long to make a new release, but in the meantime you can try a nightly release, see: #507
