### ISSUE TITLE
Warning: You are using a version of node-ipc containing malicious code

### ISSUE THREAD

**Issue by lukas-mertens** [ActivityWatch/aw-webui#330]
I just wanted to warn you about a current version of node-ipc containing https://github.com/RIAEvangelist/peacenotwar. You should probably pin your dependencies.

You can read more about it here: https://github.com/RIAEvangelist/node-ipc/issues/233

**Comment by lgg** [comment]
@ErikBjare please do NOT include this to newest releases 🙏🏻

**Comment by ErikBjare** [comment]
Thanks for the heads up!
