### ISSUE TITLE
Broken `VisTimeline` in Query Explorer (`SelectableEventView`)

### ISSUE THREAD

**Issue by NicoWeio** [ActivityWatch/aw-webui#335]
7e16e03a66b392142c6461624d49827616b40803 broke `VisTimeline`, i.e. it doesn't display events anymore, because the Query Explorer (`SelectableEventView`) leaves `bucket.id` undefined:

https://github.com/ActivityWatch/aw-webui/blob/c83e3fbd18deb0b8fd33334a5e9a0547da458aba/src/components/SelectableEventView.vue#L11

This was `bidx` before:

https://github.com/ActivityWatch/aw-webui/blob/7e16e03a66b392142c6461624d49827616b40803/src/visualizations/VisTimeline.vue#L93

This could be fixed by setting an arbitrary ID or by going back to using `bidx` in the iteration, but I assume neither option gets along with the Timeline's new editing mode (untested). I'm not sure how to proceed, so I'm posting this here as an Issue instead of a PR.

**Comment by ErikBjare** [comment]
Thanks for the report! I'll have a look soon.
