### ISSUE TITLE
Discontinue use of vue-resource in favor of aw-client-js

### ISSUE THREAD

**Issue by ErikBjare** [ActivityWatch/aw-webui#34]
vue-resource lost its official status: https://medium.com/the-vue-point/retiring-vue-resource-871a82880af4

Since using vue-resource means duplicating code for accessing the REST API, we'd be better off improving aw-client-js and using it in place of vue-resource.

Evan recommends [Axios](https://github.com/mzabriskie/axios). Definitely something to take a look at.

**Comment by ErikBjare** [comment]
Started working on implementing aw-client-js with Axios here: https://github.com/ActivityWatch/aw-client-js/pulls

**Comment by johan-bjareholt** [comment]
Works well with the axios branch https://github.com/ActivityWatch/aw-webui/pull/62

**Comment by johan-bjareholt** [comment]
Done, closing
