### ISSUE TITLE
`Tools > Trends` • TypeError: can't access property "…", e is undefined

### ISSUE THREAD

**Issue by BelKed** [ActivityWatch/aw-webui#340]
- **OS name and version:** macOS High Sierra 10.13.6
- **ActivityWatch version:** `v0.12.0b1.dev+f4cd280`
- **Browser name and version:** Firefox Developer Edition 100.0b9 (same on Google Chrome and Safari)

There are some errors when opening Tools > Trends:

![Screen Shot 2022-05-01 at 19 50 32](https://user-images.githubusercontent.com/66956532/166158460-aa1755c6-681f-424e-8030-6f94ea52ea65.png)

If I can provide something else related to this issue, feel free to write ;)

**Comment by ErikBjare** [comment]
The `Trends` view is very much a work-in-progress, it is expected to be broken (for now). 

Usually a banner appears that it's work-in-progress, but looks like the errors stopped it from showing! (I'll take a look at it)
