### ISSUE TITLE
Sunburst visualization

### ISSUE THREAD

**Issue by ErikBjare** [ActivityWatch/aw-webui#36]
Sunbursts are beautiful, simple, and supports hierarchical data perfectly for our level-of-detail visualization.

A lot of work have gone into them in the D3.js community.

 - Basic layout: https://bl.ocks.org/mbostock/4063423
 - Shows info in middle interactively on hover: https://bl.ocks.org/kerryrodden/7090426
 - Zoomable: https://bl.ocks.org/mbostock/4348373
 - This doesn't load for me, but sounds amazing: https://bl.ocks.org/mbostock/4348373
 - Curved text: http://bl.ocks.org/jebeck/196406a3486985d2b92e
    - Useful if we want to have information inside the circles.

**Comment by ErikBjare** [comment]
## Bonus idea: The Starburst

The starburst is an idea I have for a 3D version of the sunburst.

Imagine the sunburst as a clock, but instead of going back to 00:00 after 23:59, it goes to 00:00 *the next day*. How could we get rid of this discontinuity? Instead of making the clock a thick 2D arc, we turn it into a 3D spiral inwards. The outer edge of the spiral will still contain the detail-tree and we can scroll forwards and backwards in time effortlessly.

If you see the entire circle as a day clock, there is a discontinuity at the top. (Where T = 00:00). The time between l

**Comment by Powersource** [comment]
Inspiration for the starburst https://twitter.com/britishgaming/status/862043084200325123

**Comment by ErikBjare** [comment]
Woah 😮 

I like that.

**Comment by ErikBjare** [comment]
Woah 😮 

I like that.

**Comment by ErikBjare** [comment]
Alright, so a lot of initial work went into this in https://github.com/ActivityWatch/aw-webui/issues/17.

There are a bunch of issues and general suboptimalities documented in the code, added a note that it's an alpha for now.

**Comment by ErikBjare** [comment]
We just had a request for a less than 24h clock: https://github.com/ActivityWatch/activitywatch/issues/107

**Comment by ErikBjare** [comment]
This was done, so closing.

We'll do another sunburst once we have categorization working though.
