### ISSUE TITLE
Fix indentation in files

### ISSUE THREAD

**Issue by ErikBjare** [ActivityWatch/aw-webui#40]
I've managed to fuck up the supposedly 2-space indentation rule in a lot of files.

I'll partially fix the situation with a better .editorconfig in https://github.com/ActivityWatch/aw-webui/pull/39 (preventing similar future mistakes) but the indentation should probably be fixed in a separate PR to not clog down the reviewing in the above PR.

**Comment by johan-bjareholt** [comment]
Fixed by #57
