### ISSUE TITLE
"Today view"  does not refresh the chart

### ISSUE THREAD

**Issue by geneotech** [ActivityWatch/aw-webui#53]
So I have this kind of view:

![image](https://user-images.githubusercontent.com/3588717/34953801-3748420a-fa1e-11e7-95e2-d6782556dab7.png)

Even though I did some things today already.
The view worked well yesterday (which is when I've started using ActivityWatch) and it seems to be broken now - it's frozen and does not refresh now matter how much I press ``Ctrl+F5``.

The standard *Top applications* view, however, works flawlessly:

![image](https://user-images.githubusercontent.com/3588717/34953894-9c7d18b2-fa1e-11e7-981e-68291da073ce.png)

The "Top window titles" section and others on the same page have no issues as well.

My current installation is the 0.7.1 version from here:
https://github.com/ActivityWatch/activitywatch/releases/download/v0.7.1/activitywatch-v0.7.1-linux-x86_64.zip

I'm running the app via ``aw-qt``. I'm running Arch Linux with ``i3`` window manager. Another friend of mine has the same issue, also on Arch and with ``i3``, though he's running ActivityWatch through the following sequence of commands:

``
aw-server
aw-watcher-afk
aw-watcher-window
``

**Comment by johan-bjareholt** [comment]
Hm, odd.

I am running debian+i3 on my work computer and arch+bspwm on my home computer where it works, so that shouldn't be the issue at least.

I am aware of a undocumented bug where if you have a not-afk event which is during a date change (at 00:00), the forthcoming application usage the next day will not be counted until there is a new aw-watcher-afk event (which it seems to be in the today view screenshot), but in that case the today view should still work.

Could you press F12 and see if there are any javascript errors when loading the page?

**Comment by geneotech** [comment]
I believe this is where I should look for errors?

![image](https://user-images.githubusercontent.com/3588717/35043403-c818123c-fb8c-11e7-8499-6695bc508abb.png)

**Comment by johan-bjareholt** [comment]
Yeah, but there doesn't seem to be any obvious ones.
Seems like it could be hard to solve without actually being able to replicate it, I'll have a look at the code later and see if I can figure out where something could go wrong in a cornercase like this.

**EDIT: ** There are some changes to how the today view works in the next activitywatch version, it is actually rather likely that it might fix itself then.

**Comment by ErikBjare** [comment]
That first warning message in the JS console reminded me that https://github.com/ActivityWatch/activitywatch/issues/160 is a good way to harden the security of the webapp.

**Comment by johan-bjareholt** [comment]
The code has changed a lot on the master branch regarding the sunburst/today view.
Closing this until someone is able to replicate it on master or on 0.8 once that's released.
