### ISSUE TITLE
ActivityWatch View error when updating activitywatch in macOS

### ISSUE THREAD

**Issue by baker221** [ActivityWatch/aw-webui#587]
I update it from 0.12.2 to 0.13.0. And the view cannot display correctly.
<img width="802" alt="image" src="https://github.com/ActivityWatch/aw-webui/assets/43471538/126ace8e-8e35-45a4-8b9a-50fc77b8473c">

The complete info is:

<img width="492" alt="image" src="https://github.com/ActivityWatch/aw-webui/assets/43471538/1e9f8de3-9d89-431c-bc82-a1e177586e3c">

**Comment by ErikBjare** [comment]
Sorry about that, this was also reported in https://github.com/ActivityWatch/activitywatch/issues/1071, I just released https://github.com/ActivityWatch/activitywatch/releases/tag/v0.13.1 which has the fix https://github.com/ActivityWatch/aw-webui/pull/583.

If it doesn't work for you, do let me know!
