### ISSUE TITLE
Add import and export bucket functionality

### ISSUE THREAD

**Issue by ErikBjare** [ActivityWatch/aw-webui#6]
Uploading/downloading as a file would be preferable.
- [ ] Import from clipboard or by uploading file.
- [x] Export to JSON shown in modal or file. 

We should possibly also offer a way to export all buckets in one go (return a zip if possible client-side).

**Comment by ErikBjare** [comment]
Constructing a zip client-side should be possible with: https://stuk.github.io/jszip/

**Comment by johan-bjareholt** [comment]
Do we actually need this? Seems kind of unnecessary to me, at least very low priority.

**Comment by ErikBjare** [comment]
Yeah not really, trivial to write a short script that does this with the API. Closing.
