### ISSUE TITLE
Switch to Typescript?

### ISSUE THREAD

**Issue by brayo-pip** [ActivityWatch/aw-webui#615]
There are numerous type errors that are hard to reproduce that pop up from time to time. Switching to typescript would possibly fix this. It's an enormous task for sure. But I still think it should be considered. Both Typescript and Javascript can be used in the same project so, we can migrate a few files at a time.

**Comment by ErikBjare** [comment]
I've already migrated large parts to TypeScript, but I've avoided many of the Vue components (since they can be tricky to type iirc).

https://github.com/ActivityWatch/aw-webui/pulls?q=sort%3Aupdated-desc+is%3Apr+typescript+is%3Amerged

**Comment by brayo-pip** [comment]
I will get started on the rest
