### ISSUE TITLE
Start using Google Charts

### ISSUE THREAD

**Issue by ErikBjare** [ActivityWatch/aw-webui#74]
It would be nice to avoid having to maintain our own visualization code, and Google Charts is flexible and well supported.

 - The [timeline visualization](https://developers.google.com/chart/interactive/docs/gallery/timeline) is used by both Home Assistant and Sleep as Android. It's pretty clean, with nice hover-behavior.

 - The [barchart](https://developers.google.com/chart/interactive/docs/gallery/barchart)

**Comment by johan-bjareholt** [comment]
This one looks pretty sweet as well for a good overview

https://developers.google.com/chart/interactive/docs/gallery/calendar

> Would be nice to avoid having to maintain our own visualization code.

I kind of disagree with this statement though. It's easier to extend and perfectly style our own coded charts than theirs I would believe until proven wrong.

**Comment by ErikBjare** [comment]
We can't use Google Charts since they don't allow shipping it with an application (you have to use their online version). This is specifically why we ended up using to vis-timeline.
