### ISSUE TITLE
Implement visualization base class/template

### ISSUE THREAD

**Issue by Otto-AA** [ActivityWatch/aw-webui#80]
From what I've seen in the source code, there are currently several different standards (e.g. `Summary.vue`, `PeriodUsage.vue`, ...) used to display visualizations. Yet, I believe that it would be useful if we have one base class of which all these visualization classes are derived.

This could prove helpful for
- implementing new visualizations (e.g. google charts)
- let the user switch between visualization types and choose which data is being shown (especially if the user can make custom filters in the future)
- keeping the code DRY

The problem is, that I don't know if it is possible to reduce all visualizations to a common denominator. Though from what I've seen, following data should be sufficient for all currently available visualizations:
- list of events (could be filtered by date / custom filters /... before passing to visualizer)
- function which returns the data to visualize (e.g. `(event) => event.data.title`)
---------------

Here is an example base class just for demonstrating what I mean (not familiar with Vue, so just ecmascript):
```javascript
class Visualization {
 constructor() {
  this.getTargetData = (event) => {}; // e.g. (event) => event.data.title
 }
 loadEvents(events) {
  this.events = events;
 }
 redraw() {
  // Override this function
 }
 setRenderTarget(renderTarget) {
  this.renderTarget = renderTarget;
 }

}

class Summary extends Visualization {
 redraw() {
  const groupedData = this.groupEvents(this.events);
  // And somehow draw to renderTarget
 }
 groupEvents(events) {
  return events.reduce((groups, event) => {
   const groupName = this.getTargetData(event);
   if (!groups.hasOwnProperty(groupName))
    groups[groupName] = [];

   groups[groupName].push(event);
   return groups;
  });
 }
}

// Usage example
const visualizationClasses = {
  'summary': Summary,
  'timeline': Timeline
};
const visualizationType = getUserInput();
const visualization = new visualizationClasses[visualizationType]();
visualization.getTargetData = customFilter;
visualization.loadEvents(events);
visualization.redraw();
```

**Comment by johan-bjareholt** [comment]
Regardless of this, lots of visualizations needs refactoring badly (the sunburst is even unreadable to me, tried to refactor it once but gave up. it has multiple minor bugs aswell).

> The problem is, that I don't know if it is possible to reduce all visualizations to a common denominator. 

This is the reason why inheritance wouldn't add much value in this case, almost all the code is specific for each visualization anyway. Not even sure if it's possible with Vue components. Personally I think just general refactoring is what's most important here currently.

**Comment by Otto-AA** [comment]
> This is the reason why inheritance wouldn't add much value in this case, almost all the code is specific for each visualization anyway.

Actually I think that, despite them having much unique code, they don't really need unique wrappers. Without looking at the code (only at [this screenshot](https://activitywatch.net/screenshot.png)) it seems to me that passing them a list of (filtered by date/...) events and one or multiple functions which shows which data from the event to visualize, that all these visualizations should still work.

**Comment by johan-bjareholt** [comment]
True, my point is that they are not complicated as-is so there's little gain to do inheritance (if that even works with Vue components, I don't know). The APIs are not that complicated.

```
aw-periodusage(:periodusage_arr="daily_activity", :host="host")
aw-summary(:fields="top_apps", :namefunc="top_apps_namefunc", :colorfunc="top_apps_colorfunc")
aw-timeline(:events="events_apptimeline", :total_duration='duration', :show_afk='timelineShowAFK')
```

The point of subclasses is to keep the same API across similar interfaces and in this case only aw-summary and aw-timeline take the same type of events (so a good improvement would be to rename "fields" in aw-summary to "events").

The behavior is otherwise quite similar across the components, they all have a constructor for initialization and are redrawn when their events are updated. If you look at the QueryExplorer code you can see a good example of that: https://github.com/ActivityWatch/aw-webui/blob/master/src/views/QueryExplorer.vue#L39
In the .js visualization files the api is "create", "update" and optionally "set_status" on all modules. You could think that it would be a good idea to do inheritance there, but there's little gain from that since the object is the vue component and not those functions.

**Comment by Otto-AA** [comment]
From my perspective, making the visualizations inherit from a base class and thus providing a common API, would (in the future) simplify dynamically switching between visualization types/data. This could then be used, to let the user decide how to visualize and filter the data, to quickly add new visualization types and to manage a multitude of visualization types (iterating over arrays instead of hard-coding each).

But as you mentioned, this would imply using the same data format across all (standardized) visualizations, which from my point of view is the critical part. Because this could limit possible visualization forms and (to some extent) also the performance I would suggest to hard-code exceptions for these cases. Yet, from what I've seen we could rewrite nearly all (4-6 of 6) to use a common API.

I know that I tend to over-abstract things (so I am definitely a bit biased), but I think that it could/would prove useful in the future.

Regarding Vue, this seems possible with [mixins](https://vuejs.org/v2/guide/mixins.html).

**Comment by johan-bjareholt** [comment]
> From my perspective, making the visualizations inherit from a base class and thus providing a common API, would (in the future) simplify dynamically switching between visualization types/data. This could then be used, to let the user decide how to visualize and filter the data, to quickly add new visualization types and to manage a multitude of visualization types (iterating over arrays instead of hard-coding each).

You don't really need subclasses for that (as I showed you in the QueryExplorer).

> Regarding Vue, this seems possible with mixins.

Oh, nice. I'm no vue expert so was not aware.

> But as you mentioned, this would imply using the same data format across all (standardized) visualizations, which from my point of view is the critical part. Because this could limit possible visualization forms and (to some extent) also the performance I would suggest to hard-code exceptions for these cases. Yet, from what I've seen we could rewrite nearly all (4-6 of 6) to use a common API.

These are the formats each visualizer
- EventList.vue: Event list
- PeriodUsage.vue: Period list of durations
- Summary.vue: Event list
- Sunburst.vue: Fetches events and transforms it itself in some format I don't know (the black sheep)
- TimelineInspect.vue: Chunked event list
- TimelineSimple.vue: Event list

So the ones which would be able to utilize this format would be EventList, Summary and TimelineSimple, the rest require specific data structures. But still, even these three require different parameters so they can't share the same API (unless you pass unused parameters to all them).

**Comment by johan-bjareholt** [comment]
I am currently also working on improving TimelineInspect so it is more abstract and can be used for other events than window events.
