### ISSUE TITLE
Cross-Origin Request Blocked in development mode

### ISSUE THREAD

**Issue by Otto-AA** [ActivityWatch/aw-webui#82]
### Coding environment:
- Firefox 60.0.2 (64-bit)
- Node 8.10.0 (npm 6.1.0)
- Ubuntu 18.04 LTS

### Steps to reproduce:
```bash
git clone https://github.com/ActivityWatch/aw-webui/
git submodule update --recursive --init
make build
aw-qt --testing
npm run dev
```
- open http://localhost:27180

### Error
It can't connect to the aw-server because localhost:5666 doesn't seem to allow Cross-Origin Requests:
> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:5666/api/0/info. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

![Network output](https://user-images.githubusercontent.com/21040751/41639621-d4e76d64-745e-11e8-8d39-055b4221c599.png)
*Network output*
Note: An options request is automatically sent to check if it can make a CORS request ([source](https://stackoverflow.com/a/29954326/6548154)) 

![Console output](https://user-images.githubusercontent.com/21040751/41639596-b46967f4-745e-11e8-9489-51a06d5a059a.png)
*Console output*

**Comment by ErikBjare** [comment]
In order to run aw-webui in development mode you have to add `cors_origins = http://localhost:27180` to `~/.config/activitywatch/aw-server/aw-server.ini` under the `server-testing` section.

**Comment by ErikBjare** [comment]
- [ ] This should probably be added to the README
