### ISSUE TITLE
Testing mode files mixed up?

### ISSUE THREAD

**Issue by lundibundi** [ActivityWatch/aw-webui#87]
I've been trying to start webui in testing mode but it still seemed to always try to connect to prod server port
I have noticed [this](https://github.com/ActivityWatch/aw-webui/blob/master/build/dev-server.js#L6) in server file.

```js
var webpackConfig = process.env.NODE_ENV === 'testing'
  ? require('./webpack.prod.conf')
  : require('./webpack.dev.conf')
```

Shouldn't it be the opposite way around?

Then in the `webpack.prod.conf.js` I also [see](https://github.com/ActivityWatch/aw-webui/blob/master/build/webpack.prod.conf.js#L8)
```js
var env = process.env.NODE_ENV === 'testing'
  ? require('../config/test.env')
  : config.build.env
```
but `'PRODUCTION': true,` 

So I'm kinda baffled as to what's going on and wanted to point that out here.

P.S. I was finally able to start it in testing by **not** providing NODE_ENV=testing (based on the above)

**Comment by ErikBjare** [comment]
There seems to actually be three possible values for `NODE_ENV`: `production`, `development`, and `testing`.

From that it seems like the current behavior in the webpack config is actually correct. And in the following lines it seems correct that if not run in production mode the testing port should be used to connect to aw-server.
https://github.com/ActivityWatch/aw-webui/blob/cc81a9edd23985fda50fc03a73e162c017dbacc9/src/awclient.js#L3-L14

How are you trying to run the webui in testing mode? Using `make dev`?

**Comment by lundibundi** [comment]
My commands were
```
make install
aw-server --testing
npm run dev
```
Then for some reason I decided to add `NODE_ENV=testing`...
Well it all works now, thanks for your help anyways.

But it seems that 'testing' mode is actually a prod mode and webpack will [set PRODUCTION to true](https://github.com/ActivityWatch/aw-webui/blob/cc81a9edd23985fda50fc03a73e162c017dbacc9/build/webpack.prod.conf.js#L23) with it, so that snippet won't be executed.
In 'testing'  `webpack.prod.conf.js` will be included if [`NODE_ENV=testing`](https://github.com/ActivityWatch/aw-webui/blob/cc81a9edd23985fda50fc03a73e162c017dbacc9/build/dev-server.js#L6).
That's what I was trying to tell, I'm not sure if this is correct so I opened this issue.

**Comment by ErikBjare** [comment]
I think `NODE_ENV=testing` should use `PRODUCTION=true` such that tests are executed in a production-like environment. However, we never actually use `NODE_ENV=testing`, just `NODE_ENV=development`.

But you're right, `NODE_ENV=testing` should definitely use a testing server and not a production server. But since we don't even use the testing mode for now I can't be bothered to fix it :sweat_smile: 

So thanks for letting me know of this behavior (because I was unaware of it), but I'm just gonna close this for now.
